config/routes.rb
Rails.application.routes.draw do
  
  resources :paintings do
    member do
      get :like
    end
  end

  get '/login', to: 'access#login'
  post '/login' => 'access#attempt_login'
  get '/register' => 'access#register'
  post '/register' => 'access#create'
  delete '/logout' => 'access#logout'

  get '/profile' => 'access#edit'
  patch '/profile' => 'access#update'

  root to: 'paintings#index'

end

app/models/like.rb
class Like < ActiveRecord::Base

	belongs_to :painting
	belongs_to :user
	
end

app/models/painting.rb
class Painting < ActiveRecord::Base

  has_attached_file :picture, :styles => { :medium => "300x300>", :large => "600x600>" }
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  
  has_many :likes
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	
	has_many :paintings
	has_many :likes
	
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

	before_action :check_if_logged_in, except: [:login, :attempt_login, :register, :create]

	def login
		@user = User.new
	end

	def attempt_login
		user = User.where(:username => params[:username]).first
		if user && user.authenticate(params[:password])
			session[:username] = user.username
			session[:user_id] = user.id
			redirect_to root_url, notice: 'You are now logged in. Have fun!'
		else
			redirect_to '/login', notice: 'Invalid username / password.'
		end
		
	end

	def logout
		session[:user_id] = nil
		redirect_to root_url, notice: 'You are now logged out.'
	end

	def register
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, notice: 'Welcome to Art!'
		else
			render 'register'
		end
	end

	def edit
		@user = User.find(session[:user_id])
	end

	def update
		@user = User.find(session[:user_id])
		if @user.update(user_params)
			redirect_to root_path, notice: 'Profile updated'
		else
			render 'edit'
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def check_if_logged_in
  	if session[:user_id]
  		return true
  	else
  		redirect_to '/login', notice: "Log in first please!"
  		return false
  	end
  end

end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  
  before_action :check_if_logged_in
  before_action :find_painting, only: [:show, :edit, :update, :destroy]

  def index
  	@paintings = Painting.all
    @user_id = session[:user_id]
  end

  def show
  end

  def new
  	@painting = Painting.new
  end

  def create
  	@painting = Painting.new(painting_params)
    @painting.user_id = session[:user_id]
  	if @painting.save
  		redirect_to root_path, notice: 'Painting saved to database.'
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
  	if @painting.update(painting_params)
  		redirect_to @painting, notice: 'Painting updated successfully.'
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@painting.destroy
  	redirect_to root_path, notice: 'Painting deleted.'
  end

  def like
    like = Like.new
    like.user_id = session[:user_id]
    like.painting_id = params[:id]
    if like.save
      redirect_to '/', notice: 'Like registered!'
    else
      redirect_to '/', notice: 'Could not like.'
    end
  end

  private

  def find_painting
  	@painting = Painting.find(params[:id])
  end

  def painting_params
  	params.require(:painting).permit(:title, :genre, :painter, :picture)
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/access/edit.html.haml
.container
	.row
		%h3= "Editing #{@user.username}'s Profile"
		=form_for @user, url: { controller: "access", action: 'update' }do |f|
			%br
			%div.form-group.col-md-4.col-md-offset-4
				=f.text_field :username, class: 'form-control', placeholder: 'Username'
			%div.form-group.col-md-4.col-md-offset-4
				=f.text_field :email, class: 'form-control', placeholder: 'Email'
			%div.form-group.col-md-4.col-md-offset-4
				=f.password_field :password, class: 'form-control', placeholder: 'Password'
			%div.form-group.col-md-4.col-md-offset-4
				=f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm Password'
			%div.form-group.col-md-4.col-md-offset-4
				=f.submit class: 'form-control btn btn-primary'

app/views/access/login.html.haml
.container
	.row
		= form_tag action: 'attempt_login' do
			%div.form-group.col-md-4.col-md-offset-4
				= text_field_tag :username, nil, class: 'form-control', placeholder: 'Username'
			%div.form-group.col-md-4.col-md-offset-4
				= password_field_tag :password, nil, class: 'form-control', :placeholder => 'Password'
			%div.form-group.col-md-4.col-md-offset-4
				= submit_tag "Log in", class: 'btn btn-primary col-md-6 col-md-offset-3'

app/views/access/register.html.haml
.container
	.row
		%h3 Register
		= form_for @user, url: { controller: "access", action: 'create' } do |f|
			%div.form-group.col-md-4.col-md-offset-4
				= f.text_field :username, class: 'form-control', placeholder: 'Username'
			%div.form-group.col-md-4.col-md-offset-4
				= f.text_field :email, class: 'form-control', placeholder: 'Email'
			%div.form-group.col-md-4.col-md-offset-4
				= f.password_field :password, class: 'form-control', placeholder: 'Password'
			%div.form-group.col-md-4.col-md-offset-4
				= f.password_field :password_confirmation, class: 'form-control', :placeholder => 'Password Confirmation'
			%div.form-group.col-md-4.col-md-offset-4
				= submit_tag "Sign up now!", class: 'btn btn-primary col-md-6 col-md-offset-3'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Art</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class= 'background'>
		<div class=''>
			<nav id='nav' class='navbar navbar-default'>
				<div class='navbar-header'>
					<div class='container-fluid'>
						<%= link_to (image_tag 'https://upload.wikimedia.org/wikipedia/en/6/62/ART_Television_(Sri_Lanka)_(logo).png', alt: "ART"), '/' %>
					</div>
				</div>
				<ul class='nav navbar-nav navbar-right'>
					<% if session[:user_id] %>
						<li class=''><%= link_to 'Add Painting', new_painting_path %></li>
						<li class=''><a href='/profile'>Profile</a></li>
						<li class=''><%= link_to 'Log Out', '/logout', :method => 'delete' %></li>
					<% else %>
						<li><%= link_to 'Log In', '/login' %></li>
						<li><%= link_to 'Register', '/register' %></li>
					<% end %>
				</ul>
			</nav>
			<div class='flash'>
				<% if flash[:notice] %>
					<%= flash[:notice] %>
					<br /><br />
				<% end %>
			</div>
		</div>
		<%= yield %>
	</div>
	
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64782874-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/paintings/_form.html.erb
<div class='row'>
<%= form_for @painting, :html => { multipart: true } do |f| %>
	
	<div class='form-group col-md-6 col-md-offset-3'>
		<%= f.file_field :picture, class: 'form-control' %>
	</div>

	<div class='form-group col-md-6 col-md-offset-3'>
		<%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
	</div>

	<div class='form-group col-md-6 col-md-offset-3'>
		<%= f.text_field :painter, class: 'form-control', placeholder: 'Photographer' %>
	</div>

	<div class='form-group col-md-6 col-md-offset-3'>
		<%= f.text_field :genre, class: 'form-control', placeholder: 'Genre' %>
	</div>

	<div class='form-group col-md-6 col-md-offset-3'>
		<div class='row'>
			<div class='col-md-12'>
				<%= f.submit "Add Photo", class: 'btn btn-primary btn-block' %>
			</div>
		</div>
	</div>

<% end %>
</div>

app/views/paintings/edit.html.erb
<div class='row' >
	<div class='col-md-6 col-md-offset-3'>
		<h3>Edit Photo</h3>
		<%= image_tag @painting.picture.url(:medium), class: 'col-md-offset-3 col-md-6' %>
		<div style='display:block;height:250px'></div>
		<%= render 'form' %>
	</div>
</div>

app/views/paintings/index.html.erb
<div class='container'>
	<p>Next level Brooklyn shabby chic, bicycle rights meh aesthetic sartorial cardigan you probably haven't heard of them chambray lomo dreamcatcher small batch before they sold out freegan. Food truck distillery fashion axe, YOLO stumptown tousled flannel Helvetica bitters disrupt cronut Shoreditch. Lumbersexual cred kitsch, wolf listicle asymmetrical actually. Bitters American Apparel skateboard, blog art party umami Kickstarter irony mustache mumblecore disrupt stumptown. Gluten-free keytar messenger bag PBR&B, Wes Anderson readymade meditation 90's. Brooklyn cliche pork belly dreamcatcher. Irony Vice Intelligentsia bitters ennui, skateboard try-hard Echo Park iPhone keytar.</p>

	<div class='container index-row transitions-enabled'>
		<div class='row'>
		<% @paintings.each do |p| %>
			<div class='index-item'>
				<div class='panel panel-default'>
					<div class='panel-body'>
						<%= link_to (image_tag p.picture.url(:medium)), p %>
					</div>
					<div class='panel-footer'>
						<br/>
						<p><strong><%= p.title %></strong><span class='pull-right'><%= p.likes.count %> <span class='glyphicon glyphicon-heart'></span></span><br />
							By <%= p.user.email %>
							<% if p.likes.find_by_user_id(@user_id) == nil %>
							<%= link_to 'Like', like_painting_path(p), class: 'pull-right btn btn-default' %>
							<% end %>
						</p>
					</div>
				</div>
			</div>
		<% end %>
		</div>
	</div>
</div>

app/views/paintings/new.html.erb
<div class='row'>
	<div class='col-md-6 col-md-offset-3'>
		<h3 class='text-center'>Add a photo to the colection</h3>
		<br />
		<%= render 'form' %>
	</div>
</div>

app/views/paintings/show.html.erb
<div class='container show-item'>
	<div class='col-md-6 col-md-offset-3'>
	<div class='panel panel-default'>
		
		<div class='panel-heading'>
			<h1 class='panel-title'><%= @painting.title %></h1>
		</div>
		
		<div class='panel-body'>
			<%= image_tag @painting.picture.url(:large) %>
		</div>
		
		<div class='panel-footer'>
			painted by <%= @painting.painter %>
			<br />
			<%= link_to 'Edit', edit_painting_path, class: 'btn btn-default' %>
			<%= link_to 'Delete', painting_path, method: 'delete', class: 'btn btn-default delete-item' %>
		</div>
	</div>
	</div>
</div>